export const certificationsData = [
    {
        id: 1,
        title: "Certification 1",
        issuer: "Issuer 1",
        issueDate: "Sep 2022",
        credentialID: "1234567890",
        credentialURL: "https://google.com",
        description: null,
    },
    {
        id: 2,
        title: "Certification 2",
        issuer: "Issuer 2",
        issueDate: "Sep 2022",
        credentialID: "1234567890",
        credentialURL: "https://google.com",
        description: null,
    },
    ,
    {
        id: 3,
        title: "Certification 3",
        issuer: "Issuer 3",
        issueDate: "Sep 2022",
        credentialID: "1234567890",
        credentialURL: "https://google.com",
        description: null,
    },
    {
        id: 4,
        title: "Certification 4",
        issuer: "Issuer 4",
        issueDate: "Sep 2022",
        credentialID: "1234567890",
        credentialURL: "https://google.com",
        description: null,
    },
    {
        id: 5,
        title: "Certification 5",
        issuer: "Issuer 5",
        issueDate: "Sep 2022",
        credentialID: "1234567890",
        credentialURL: "https://google.com",
        description: null,
    },
    {
        id: 6,
        title: "Certification 6",
        issuer: "Issuer 6",
        issueDate: "Sep 2022",
        credentialID: "1234567890",
        credentialURL: "https://google.com",
        description: null,
    },
    {
        id: 7,
        title: "Certification 7",
        issuer: "Issuer 7",
        issueDate: "Sep 2022",
        credentialID: "1234567890",
        credentialURL: "https://google.com",
        description: null,
    },
    {
        id: 8,
        title: "Certification 8",
        issuer: "Issuer 8",
        issueDate: "Sep 2022",
        credentialID: "1234567890",
        credentialURL: "https://google.com",
        description: null,
    },
    {
        id: 9,
        title: "Certification 9",
        issuer: "Issuer 9",
        issueDate: "Sep 2022",
        credentialID: "1234567890",
        credentialURL: "https://google.com",
        description: null,
    },
    {
        id: 10,
        title: "Certification 10",
        issuer: "Issuer 10",
        issueDate: "Sep 2022",
        credentialID: "1234567890",
        credentialURL: "https://google.com",
        description: null,
    }
];