export const experienceData = [
     {
        id: 1,
        position: "Sr. Email Marketing Designer",
        duration: "Nov 2024 - Present",
        company: "Enflow Digital",
        companyLink: "https://enflowdigital.com/",
        address: "Remote",
        description: "Design and optimize visually engaging, on-brand email templates for effective marketing campaigns across various devices and platforms.",
    },
    {
        id: 2,
        position: "Mentor, UI/UX Designer",
        duration: "Jun 2024 - Sep 2024",
        company: "Vona Tech Community",
        companyLink: "https://vonatechcommunity.com/",
        address: "Worldwide, UA",
        description: "Guide mentees in developing skills, executing projects, and contributing to industry growth through mentorship and collaboration.",
    },
    {
        id: 3,
        position: "Email Marketing Designer, UI/UX Designer",
        duration: "Sep 2021 - Nov 2024",
        company: "IMPRO Email agency",
        companyLink: "https://impro.email/",
        address: "Lviv, UA",
        description: "Accomplishing  Banners, gifs and other graphic elements from scratch, attracting attention with the help of design. Thinking of solutions to solve business problems with the help of design.",
    },
    {
        id: 4,
        position: "UI/UX Designer, SMM Designer",
        duration: "Jan 2020 - Sep 2021",
        company: "Freelance",
        companyLink: "https://google.com",
        address: "Remote",
        description: "Creating landing pages, competitor analysis, mockups and prototyping. Posting content on social media, designing graphic material, and attracting consumers via social media.",
    },
];
